config/routes.rb
Rails.application.routes.draw do
  resources :prints, only: [:index, :new, :create, :destroy]
  root "prints#index"
  
  

  

end

app/models/print.rb
class Print < ActiveRecord::Base

  mount_uploader :attachment, AttachmentUploader #dis à Rails d'utiliser cet uploader pour ce model.
  validates :name, presence: true # Make sure the owner's name is present.

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/prints_controller.rb
class PrintsController < ApplicationController
  def index
 
    @prints = Print.all
 
  end

  def new
    @print = Print.new
  end

  def create
    @print = Print.new(print_params)
    
    if @print.save
      redirect_to prints_path, notice: "The print #{@print.name} has been uploaded."
    else
      render "new"
    end
    
  end

  def destroy
    @print = Print.find(params[:id])
    @print.destroy
    redirect_to prints_path, notice: "The print #{@print.name} has been deleted."
  end
  
private 
  def print_params
    params.require(:print).permit(:name, :attachment, :materiau, :qualite, :livraison)  
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prints_helper.rb
module PrintsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FabrikApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/prints/create.html.erb
<h1>Prints#create</h1>
<p>Find me in app/views/prints/create.html.erb</p>

app/views/prints/destroy.html.erb
<h1>Prints#destroy</h1>
<p>Find me in app/views/prints/destroy.html.erb</p>

app/views/prints/index.html.erb
<h1>Prints#index</h1>
<p>Find me in app/views/prints/index.html.erb</p>

<% if !flash[:notice].blank?%>
	<div class="alert-info">
		<%= flash[:notice]%>
	<div>
<% end %>
<br />
<%= link_to "New Print", new_print_path, class: "btn btn-primary"%>
<br / >
<br/ >
<table class="table table-bordered table-striped">
	<thead>
		<tr>
			<th>Name</th>
			<th>Download Link </th>
			<th> Matériau </th>
			<th> Qualité </th>
			<th> Livraison </th>
			<th> </th>
		</tr>
	</thead>
	
	<tbody>
		<% @prints.each do |print| %>
		<tr>
			<td><%= print.name %></td>
			<td><%= link_to "Download File", print.attachment_url %></td>
			<td><%= print.materiau %></td>
			<td><%= print.qualite %></td>
			<td><%= print.livraison%></td>
			<td><%= button_to "Delete", print, method: :delete, class: "btn 			btn-danger", confirm: "Supprimer l'impression ? L'action est 			irreversible."%>
		</tr>
		<% end %>
	</tbody>
</table>
			

app/views/prints/new.html.erb
<h1>Prints#new</h1>
<p>Find me in app/views/prints/new.html.erb</p>

<% if !@print.errors.empty? %>
	<div class="alert-error">
		<ul>
			<% @print.errors.full_messages.each do |msg|%>
			<li> <%= msg %></li>
			<% end %>
		</ul>
<% end %>

<div class="well">
		<%= form_for @print, html: { :multipart => true } do |f| %>
			<%= f.label :name %>
			<%= f.text_field :name %>
			<%= f.label :attachment %>
			<%= f.file_field :attachment %>
			
			<%= f.submit "save", class: "btn btn-primary"%>
		<% end %>
</div>